name: GitHub Pages Deploy

on:
  push:
    branches: ["ebobo"]
    paths:
      - "client/**"
      - "shared/**"
      - ".github/workflows/**"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: ./client
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config

      - name: Install Rust
        working-directory: ./client
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env
          rustup target add wasm32-unknown-unknown

      - name: Install Trunk
        working-directory: ./client
        run: |
          cargo install --locked trunk

      - name: Build
        working-directory: ./client
        run: |
          cargo build --target wasm32-unknown-unknown --release

      - name: Build with Trunk
        working-directory: ./client
        run: |
          trunk build --release

      - name: Setup pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './client/dist'
          
      - name: Deploy to pages
        id: deployment
        uses: actions/deploy-pages@v2